apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
config:
  xpack.fleet.packages:
    - name: apm
      version: 8.17.3
metadata:
  name: dev-kibana
spec:
  version: 8.17.3
  count: 1
  elasticsearchRef:
    name: dev-elasticsearch
  http:
    service:
      spec:
        type: LoadBalancer
