apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: dev-elasticsearch
  namespace: elastic-stack
spec:
  version: 8.17.3
  nodeSets:
    - name: masters
      count: 1
      config:
        node.roles: ["master"]
        xpack.ml.enabled: true
    - name: data
      count: 3
      config:
        node.roles: ["data", "ingest", "ml", "transform"]
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: longhorn
