apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-cluster
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  sources:
    - repoURL: https://charts.rook.io/release # 외부 Helm Chart Repository
      chart: rook-ceph-cluster
      targetRevision: v1.16.2
      helm:
        valueFiles:
          - $values/GitOps/helm-rook-ceph/rook-dev-values/dev-rook-cluster.yaml # Git에서 가져온 values 파일 참조

    - repoURL: https://github.com/Cloud-Web-Platform/Atlas-PlayGround.git
      targetRevision: develop
      ref: values # Helm valueFiles에서 참조할 변수 이름

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
