grafana:
  persistence:
    enabled: true
    storageClassName: "longhorn" # Longhorn 스토리지 클래스 사용
    accessModes:
      - ReadWriteOnce
    size: 5Gi # 필요에 따라 크기 조정
  service:
    type: NodePort
    nodePort: 30100
  adminPassword: "admin"
