prometheus:
  prometheusSpec:
    webSpec:
      tlsConfig:
        insecureSkipVerify: true

    # false로 설정하면, Helm 차트에 정의된 release라벨을 기준으로 ServiceMonitor를 필터링하지 않습니다.
    # 모든 ServiceMonitor 리소스를 기본적으로 선택 대상으로 포함합니다.
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
      # matchExpressions:
      #   - key: rook-ceph
      #     operator: In
      #     values: ["enabled"]
      #   - key: name
      #     operator: In
      #     values: ["system-monitoring"]

  service:
    type: NodePort
    nodePort: 30090

prometheusOperator:
  admissionWebhooks:
    failurePolicy: Ignore
  tls:
    enabled: false